---
title: Sanky Diagram
author: Rikiya Honda
date: '2021-04-05'
slug: []
categories:
  - note
tags:
  - riverplot
description: ''
thumbnail: ''
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(message = FALSE,
                      warning = FALSE,
                      fig.height = 6,
                      fig.width = 7)
Sys.setenv(lang = "en")
```

### 動作環境
```{r}
version
```

### パッケージの準備

data wanglingで必要となる一般的なパッケージ`tidyverse`とSanky Diagramで必要な`riverplot`を準備します。

```{r, echo=TRUE, results='hide', message=FALSE}
Packages <- c("tidyverse", "riverplot")
lapply(Packages, library, character.only = TRUE)
```


### Sanky Diagramとは？

Sanky Diagramとは、[こんなやつ](https://en.wikipedia.org/wiki/Sankey_diagram)です。(相変わらず、、画像のアップロードが分からないww)

川の流れになっている部分が、その変化の割合に比例しているグラフです。

といっても、百聞は一見にしかずなので、コードを見ていきましょう！

### コード
```{r}
# edgesを作成 (edgesのイメージはデータベース)
edges <- data.frame(
  N1=c("総議席","改選","改選","改選","改選","改選","改選","改選","改選","改選","総議席"),
N2=c("改選","無所属","諸派","社民","維新","共産","みんな","公明","民主","自民","非改選"),
Value=c(121,2,1,1,8,8,8,11,17,65,121),stringsAsFactors = F
)
edges

# nodesを作成
nodes <- data.frame(ID = unique(c(edges$N1, edges$N2)), stringsAsFactors = FALSE)
nodes$x <- c(1, 2, rep(3,10)) #　次元を設定
nodes

# ripverplotの作成
rp <- list(nodes = nodes, edges = edges)
class(rp) <- c(class(rp), "riverplot")
plot(rp, plot_area = 0.95, gravity = "top")
```


きれいにかけましたね。

これだけだと無粋なので、色をつけていきましょう。

```{r}
# ラベルの位置を調整する
nodes$labels = c("　　　　総議席","改選　　　","無所属　　　","諸派　　　","社民　　　","維新　　　",
"共産　　　","みんな　　　","公明　　　","民主　　　","自民　　　","非改選　　　")

library(RColorBrewer)
palette <- brewer.pal(12, "Set3")
styles = lapply(1:12, function(n) {
  list(col = palette[n])
})
names(styles) = nodes$ID
rp <- list(nodes = nodes, edges = edges, styles = styles)
class(rp) <- c(class(rp), "riverplot")
plot(rp, plot_area = 0.95, gravity = "top")
```

### 最後に、、、

今回は、以下のサイト様のコピペになってしまいましたね。

最後まで読んでいただきありがとうございました。

Adios!!

### 参考文献
* [riverplot.pdf](https://cran.r-project.org/web/packages/riverplot/riverplot.pdf)
* (https://statrstart.github.io/2015/06/28/%E3%82%B5%E3%83%B3%E3%82%AD%E3%83%BC%E3%83%BB%E3%83%80%E3%82%A4%E3%82%A2%E3%82%B0%E3%83%A9%E3%83%A01/)

