---
title: ウェブサイト更新再開！
author: Rikiya Honda
date: '2021-02-09'
slug: website-restart
categories:
  - blog
tags:
  - blogdown
description: ''
thumbnail: ''
---


こんにちは！！

久しぶりの投稿ですね。

ちょっとこのサイトを運営している`blogdown`というパッケージで問題がおきまして、更新が遅れていました。

結局のところ`R.profile`というドキュメントが邪魔をしていたらしく、削除したところ、上手くローカルでの変更がサイトに反映されるようになりました。

` R.profile`は、` getwd()`でカレントディレクトリがプロジェクトのあるディレクトリにあることを確認したのち、` file.edit("R.profile")`とコンソールに打ち込むことで生成されます。

` R.profile`のを作るメリットは、プロジェクトを立ち上げた時に自動的に読みこまれることです。

例えば、

```{r, eval=FALSE}
library(tidyverse)
```

と` R.profile`に書いておけば、毎回か必ずそのコードがrunされます。

沢山のlibraryを使っている時に特に威力を発揮します。

が、今回は`blogdown`との間で何らかの障害が発生したらしく、上手くサイトが生成されませんでした。

追記：
`?blogdown::serve_site()`で関数の仕様を確認すると、「RMarkdownでは、毎回は上手くいかないかも。でも、Markdownなら問題なし！」的なことがちゃっかり書いてありました。（訳適当）

>this automatic navigation may not always work for R Markdown posts, and you may have to manually refresh your browser. It should work reliably for pure Markdown posts, though.

追記②：
"`r パッケージ（or 関数）`という形で間違って書いていたことも原因かもしれません。

是非気をつけたいですね。


原因は分からないのですが、結果ウェブの更新を再開できるようになって良かったです。

慣れてきたようで、R言語は難しいな～

では、また次回会いましょう！

最後まで読んでいただきありがとうございます！

Adios!!
