---
title: 3Dデータの作成
author: Rikiya Honda
date: '2021-02-11'
slug: 3D-graphics
categories:
  - note
tags:
  - rgl
  - threejs
---

こんにちは！

今回は、３Dプロットのまとめをまとめました。

たぶんインタラクティブなグラフになっているので、触れあってみてください！

では、見ていきましょう！

```{r setup, include=FALSE}
knitr::opts_chunk$set(message = FALSE,
                      warning = FALSE,
                      fig.height = 6,
                      fig.width = 7)
Sys.setenv(lang = "en")
```


## 環境

```{r}
version
```



```{r}
# setup library()

library(tidyverse)
library(rgl)
library(threejs)

# plot 3d static graphs

plot3d(xyz) # これはローカル環境でしか動作しない。

# plot 3d graph with `threejs`

z <- seq(-10, 10, by = 0.1)
x <- cos(z)
y <- sin(z)
scatterplot3js(x, y, z, 
               color = rainbow(length(z)),
               num.tricks = c(6, 6, 6),
               x.tricklabs = NULL,
               y.tricklabs = NULL,
               z.tricklabs = NULL,
               size = 1,
               )

# animation with rgl & htmltools

# setup library()

library(rgl)
library(htmltools)

# theta を定義
theta <- seq(0, 6*pi, len = 100) 

# xyz軸を定義
xyz <- cbind(sin(theta), cos(theta), theta)

# plot3dで図を表示させる
lineid <- plot3d(xyz, type = "l", alpha = 1:0,
                 lwd = 5, col = "blue")["data"]


# 図を動かす
browsable(tagList( # tagを作成（たぶん）
  rglwidget(elementId = "example", # ここでrglwidgetの名称をつける 
            width = 500, height = 400, # 表示するピクセル数
            controllers = "player"), # コントローラーの名称をつける
  playwidget("example",
             ageControl(births = theta, 
                        ages = c(0, 0, 10), # xyzの順
                        objids = lineid, 
                        alpha = c(0, 1, 0)),
                        start = 1, stop = 6*pi, # スタートする位置の値 
                        step = 0.1, # 0.1ずつ動く
                        rate = 6, # 単位を実世界の毎秒あたりいくつ動かすか 
                        elementId = "player") # ??
))


```

## 最後に、、、

いかがだったでしょうか？

案外、きれいに出力できますね。

と思ったら、3dの図は出力されていませんね。。。

たぶんこのサイトの仕様の問題だと思います。

コードだけなら参考になるかなww

最後まで読んでいきだきありがとうございました。


Adios!!
